import type {
  AssignmentGameLevel,
  AssignmentGameTileAsset,
  AssignmentGameTileId,
} from './assignmentGameLevelTypes';

const tileAssetBasePath = '/assets/assignment-game/tiles';

export const assignmentGameTileAssets: Record<AssignmentGameTileId, AssignmentGameTileAsset> = {
  stoneFloor: {
    label: 'Stone floor',
    src: `${tileAssetBasePath}/tile_stone_floor.png`,
    fallbackBackground:
      'linear-gradient(135deg, rgba(105, 109, 132, 0.86), rgba(49, 44, 70, 0.94))',
  },
  crackedStoneFloor: {
    label: 'Cracked stone floor',
    src: `${tileAssetBasePath}/tile_cracked_stone_floor.png`,
    fallbackBackground:
      'linear-gradient(135deg, rgba(116, 105, 122, 0.88), rgba(37, 35, 57, 0.96))',
  },
  grassEdge: {
    label: 'Grass edge',
    src: `${tileAssetBasePath}/tile_grass_edge.png`,
    fallbackBackground:
      'linear-gradient(135deg, rgba(51, 126, 90, 0.72), rgba(39, 74, 62, 0.9))',
  },
  dirtPath: {
    label: 'Dirt path',
    src: `${tileAssetBasePath}/tile_dirt_path.png`,
    fallbackBackground:
      'linear-gradient(135deg, rgba(118, 76, 44, 0.88), rgba(62, 43, 36, 0.96))',
  },
  castleWall: {
    label: 'Castle wall',
    src: `${tileAssetBasePath}/tile_castle_wall.png`,
    fallbackBackground:
      'linear-gradient(180deg, rgba(79, 84, 117, 0.95), rgba(31, 30, 52, 0.98))',
  },
  castleWallTop: {
    label: 'Castle wall top',
    src: `${tileAssetBasePath}/tile_castle_wall_top.png`,
    fallbackBackground:
      'linear-gradient(180deg, rgba(109, 113, 142, 0.96), rgba(48, 45, 72, 0.98))',
  },
  castleCorner: {
    label: 'Castle corner',
    src: `${tileAssetBasePath}/tile_castle_corner.png`,
    fallbackBackground:
      'linear-gradient(135deg, rgba(128, 126, 153, 0.96), rgba(36, 34, 58, 0.98))',
  },
  stairs: {
    label: 'Stairs',
    src: `${tileAssetBasePath}/tile_stairs.png`,
    fallbackBackground:
      'repeating-linear-gradient(180deg, rgba(132, 120, 112, 0.95) 0 9px, rgba(71, 65, 70, 0.95) 9px 18px)',
  },
  shadow: {
    label: 'Shadow',
    src: `${tileAssetBasePath}/tile_shadow.png`,
    fallbackBackground:
      'radial-gradient(circle, rgba(0, 0, 0, 0.58), rgba(0, 0, 0, 0.12) 68%, transparent 72%)',
  },
  waterOrVoid: {
    label: 'Water or void',
    src: `${tileAssetBasePath}/tile_water_or_void.png`,
    fallbackBackground:
      'linear-gradient(135deg, rgba(19, 35, 72, 0.96), rgba(23, 6, 44, 0.98))',
  },
  lockedBoundary: {
    label: 'Locked magical boundary',
    src: `${tileAssetBasePath}/tile_locked_boundary.png`,
    fallbackBackground:
      'radial-gradient(circle, rgba(255, 176, 0, 0.78), rgba(255, 43, 214, 0.28) 54%, rgba(25, 9, 42, 0.94) 72%)',
  },
};

export const ruinedCourtyardLevel = {
  id: 'ruined-courtyard',
  name: 'Ruined Courtyard',
  objectiveText:
    'Survey the Ruined Courtyard and find the sealed Ember Gate. Combat, dialogue, inventory, and saves are not active yet.',
  dimensions: {
    columns: 12,
    rows: 8,
    tileSize: 64,
  },
  playerSpawn: {
    x: 18,
    y: 72,
  },
  movementBounds: {
    minX: 8,
    maxX: 92,
    minY: 17,
    maxY: 86,
  },
  tileRows: [
    [
      'castleCorner',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleCorner',
    ],
    [
      'castleWall',
      'grassEdge',
      'stoneFloor',
      'crackedStoneFloor',
      'stoneFloor',
      'lockedBoundary',
      'lockedBoundary',
      'crackedStoneFloor',
      'stoneFloor',
      'stoneFloor',
      'grassEdge',
      'castleWall',
    ],
    [
      'castleWall',
      'stoneFloor',
      'crackedStoneFloor',
      'stoneFloor',
      'dirtPath',
      'dirtPath',
      'dirtPath',
      'stoneFloor',
      'crackedStoneFloor',
      'stoneFloor',
      'stoneFloor',
      'castleWall',
    ],
    [
      'castleWall',
      'stoneFloor',
      'stoneFloor',
      'dirtPath',
      'dirtPath',
      'crackedStoneFloor',
      'dirtPath',
      'dirtPath',
      'stoneFloor',
      'grassEdge',
      'stoneFloor',
      'castleWall',
    ],
    [
      'castleWall',
      'grassEdge',
      'stoneFloor',
      'dirtPath',
      'stoneFloor',
      'stoneFloor',
      'stoneFloor',
      'dirtPath',
      'crackedStoneFloor',
      'stoneFloor',
      'grassEdge',
      'castleWall',
    ],
    [
      'castleWall',
      'stoneFloor',
      'crackedStoneFloor',
      'stoneFloor',
      'stoneFloor',
      'grassEdge',
      'stoneFloor',
      'stoneFloor',
      'dirtPath',
      'dirtPath',
      'stoneFloor',
      'castleWall',
    ],
    [
      'castleWall',
      'stairs',
      'stairs',
      'dirtPath',
      'stoneFloor',
      'stoneFloor',
      'crackedStoneFloor',
      'stoneFloor',
      'dirtPath',
      'stoneFloor',
      'grassEdge',
      'castleWall',
    ],
    [
      'castleCorner',
      'waterOrVoid',
      'waterOrVoid',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'castleWallTop',
      'waterOrVoid',
      'waterOrVoid',
      'waterOrVoid',
      'castleCorner',
    ],
  ],
  blockedZones: [
    { id: 'north-wall', label: 'North castle wall', x: 0, y: 0, width: 12, height: 1 },
    { id: 'west-wall', label: 'West castle wall', x: 0, y: 0, width: 1, height: 8 },
    { id: 'east-wall', label: 'East castle wall', x: 11, y: 0, width: 1, height: 8 },
    { id: 'south-void', label: 'Collapsed southern void', x: 1, y: 7, width: 2, height: 1 },
    { id: 'sealed-gate', label: 'Sealed Ember Gate', x: 5, y: 1, width: 2, height: 1 },
    { id: 'lower-right-void', label: 'Lower right void', x: 8, y: 7, width: 3, height: 1 },
  ],
  features: [
    {
      id: 'entry-stairs',
      label: 'Courtyard entrance stairs',
      kind: 'entrance',
      tileId: 'stairs',
      x: 1,
      y: 6,
      width: 2,
      height: 1,
    },
    {
      id: 'ember-gate',
      label: 'Locked Ember Gate',
      kind: 'lockedGate',
      tileId: 'lockedBoundary',
      x: 5,
      y: 1,
      width: 2,
      height: 1,
    },
    {
      id: 'north-gate-shadow',
      label: 'Gate shadow',
      kind: 'shadow',
      tileId: 'shadow',
      x: 5,
      y: 2,
      width: 2,
      height: 1,
    },
    {
      id: 'west-boundary-glow',
      label: 'West magical boundary',
      kind: 'boundary',
      tileId: 'lockedBoundary',
      x: 0,
      y: 2,
      width: 1,
      height: 4,
    },
    {
      id: 'east-boundary-glow',
      label: 'East magical boundary',
      kind: 'boundary',
      tileId: 'lockedBoundary',
      x: 11,
      y: 2,
      width: 1,
      height: 4,
    },
  ],
} as const satisfies AssignmentGameLevel;
